disabled_rules: # rule identifiers turned on by default to exclude from running
  - cyclomatic_complexity
  - sorted_imports
  - nesting
  - identifier_name
  - type_name
  - function_body_length
  - type_body_length
  - trailing_whitespace

opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - anyobject_protocol
  - unused_import
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - private_outlet
  - redundant_nil_coalescing
  - vertical_whitespace_closing_braces
  - yoda_condition

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

line_length: 200
file_length: 600
large_tuple: 6